INSERT INTO users (name, password, email) VALUES ('Administrador', 1234,  'prueba1@gmail.com');
INSERT INTO users (name, password, email) VALUES ('Secretaria', 5678, 'prueba2@gmail.com');
INSERT INTO users (name, password, email) VALUES ('Estudiante', 9012, 'prueba3@gmail.com');
INSERT INTO users (name, password, email) VALUES ('Docente', 3456, 'prueba4@gmail.com');
INSERT INTO users (name, password, email) VALUES ('Tesoreria', 7890, 'prueba5@gmail.com');
INSERT INTO users (name, password, email) VALUES ('Registro Control', 1234, 'prueba6@gmail.com');
INSERT INTO productos_favoritos (name_producto, descripcion) VALUES ('Sala1', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s');
INSERT INTO productos_favoritos (name_producto, descripcion) VALUES ('Sala2', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s');
INSERT INTO productos_favoritos (name_producto, descripcion) VALUES ('Sala3', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s');
INSERT INTO productos_favoritos (name_producto, descripcion) VALUES ('Sala4', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s');
INSERT INTO productos_favoritos (name_producto, descripcion) VALUES ('Sala5', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s');
